const menuobj = [
  {
    id: "fruitteasection",
    section: "Fruit Teas",
    items: [
      {
        id: 1,
        htmlid: "mangojasmine",
        name: "Mango Jasmine Tea",
        image: "/assets/Final/mango_small.jpg",
      },

      {
        id: 2,
        htmlid: "lycheefruittea",
        name: "Lychee Jasmine Tea",
        image: "/assets/Final/lychee_small.jpg",
      },
      {
        id: 3,
        htmlid: "passionfruittea",
        name: "Passionfruit Jasmine Tea",
        image: "/assets/Final/passion_small.jpg",
      },
    ],
  },

  {
    id: "milkteasection",
    section: "Milk Teas",
    items: [
      {
        id: 4,
        htmlid: "jasminemilktea",
        name: "Jasmine Milk Tea",
        image: "/assets/Final/jasmine_jelly_small.jpg",
      },

      {
        id: 5,
        htmlid: "oolongmilktea",
        name: "Roasted Oolong Milk Tea",
        image: "../assets/Final/oolong_jelly_small.jpg",
      },
      {
        id: 6,
        htmlid: "matchamilktea",
        name: "Matcha Milk Tea",
        image: "/assets/Final/matcha_small.jpg",
      },

      {
        id: 7,
        htmlid: "taromilktea",
        name: "Taro Milk Tea",
        image: "/assets/Final/taro_small.jpg",
      },

      {
        id: 8,
        htmlid: "coffeemilktea",
        name: "Coffee Milk Tea",
        image: "/assets/Final/coffee_mt_small.jpg",
      },
    ],
  },

  {
    id: "specialsection",
    section: "Specialty Drinks",
    items: [
      {
        id: 9,
        htmlid: "thaiicedtea",
        name: "Thai Iced Tea",
        image: "/assets/Final/thai_tea_small.jpg",
      },

      {
        id: 10,
        htmlid: "vietnamesecoffee",
        name: "Vietnamese Coffee",
        image: "/assets/Final/coffee_small.jpg",
      },
      {
        id: 11,
        htmlid: "mangolassi",
        name: "Mango Lassi",
        image: "/assets/Final/lassi-removebg-preview.png",
      },
    ],
  },
];

const allItems = [
  {
    id: 1,
    htmlid: "mangojasmine",
    name: "Mango Jasmine Tea",
    image: "../assets/Final/mango_small.jpg",
    desc: "Indulge in the refreshing harmony of tropical bliss with our Mango Jasmine Tea. This exquisite blend combines the luscious sweetness of ripe mangoes with the delicate floral notes of jasmine, creating a tantalizing fusion of flavors. Sip on this aromatic infusion and let the vibrant mango essence transport you to sun-kissed tropical shores, while the soothing jasmine petals offer a serene and aromatic experience. Elevate your tea ritual with the exotic allure of Mango Jasmine Tea.",
    smallName: "Mango Jasmine Tea Small",
    largeName: "Mango Jasmine Tea Large",
    nutrition: {
      //correct
      small: {
        serving_size: 420,
        calories: 144,
        total_fat: [0, 0],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [35, 13],
        dietary_fiber: [0, 0],
        total_sugars: 24,
        added_sugars: [0, 0],
        protein: [1, 2],
      },

      large: {
        serving_size: 546,
        calories: 187,
        total_fat: [18, 23],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [64, 13],
        dietary_fiber: [0, 0],
        total_sugars: 39,
        added_sugars: [0, 0],
        protein: [1, 2],
      },
    },
  },

  {
    id: 2,
    htmlid: "lycheefruittea",
    name: "Lychee Jasmine Tea",
    image: "../assets/Final/lychee_small.jpg",
    desc: "Embark on a delightful journey with our Lychee Jasmine Tea. This exquisite blend combines the succulent sweetness of lychee fruit with the enchanting fragrance of jasmine, resulting in a tea that is both refreshing and captivating. Immerse yourself in the harmonious fusion of tropical lychee and aromatic jasmine, and let this tea transport you to a serene oasis of taste and tranquility. Treat yourself to the irresistible charm of Lychee Jasmine Tea and discover a moment of pure bliss in every sip. ",
    smallName: "Lychee Jasmine Tea Small",
    largeName: "Lychee Jasmine Tea Large",
    nutrition: {
      //correct
      small: {
        serving_size: 420,
        calories: 144,
        total_fat: [0, 0],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [35, 13],
        dietary_fiber: [0, 0],
        total_sugars: 24,
        added_sugars: [0, 0],
        protein: [1, 2],
      },

      large: {
        serving_size: 546,
        calories: 187,
        total_fat: [0, 0],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [46, 13],
        dietary_fiber: [0, 0],
        total_sugars: 31,
        added_sugars: [0, 0],
        protein: [1, 2],
      },
    },
  },
  {
    id: 3,
    htmlid: "passionfruittea",
    name: "Passionfruit Jasmine Tea",
    image: "../assets/Final/passion_small.jpg",
    desc: "Experience a burst of passion with our tantalizing Passionfruit Jasmine Tea. This enchanting blend combines the exotic tanginess of passionfruit with the delicate allure of jasmine, creating a harmonious symphony of flavors. Discover a captivating tea experience that will awaken your senses and leave you craving for more. Embrace the passion of our Passionfruit Jasmine Tea and let its vibrant flavors sweep you away.",
    smallName: "Passion Fruit Jasmine Tea Small",
    largeName: "Passion Fruit Jasmine Tea Large",
    nutrition: {
      //correct
      small: {
        serving_size: 420,
        calories: 167,
        total_fat: [1, 1],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [43, 16],
        dietary_fiber: [0, 0],
        total_sugars: 38,
        added_sugars: [0, 0],
        protein: [0, 0],
      },

      large: {
        serving_size: 546,
        calories: 217,
        total_fat: [1, 1],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [56, 16],
        dietary_fiber: [0, 0],
        total_sugars: 49,
        added_sugars: [0, 0],
        protein: [0, 0],
      },
    },
  },
  {
    id: 4,
    htmlid: "jasminemilktea",
    name: "Jasmine Milk Tea",
    image: "../assets/Final/jasmine_jelly_small.jpg",
    desc: "Unwind with the enchanting embrace of Jasmine Milk Tea. This soothing beverage combines the delicate floral essence of jasmine tea with the creamy indulgence of milk. With each sip, you'll be captivated by the aromatic notes of jasmine, which infuse the tea with a sense of tranquility and relaxation.",
    smallName: "Jasmine Milk Tea Small",
    largeName: "Jasmine Milk Tea Large",
    smallNameNB: "Jasmine Milk Tea Non Boba Small",
    largeNameNB: "Jasmine Milk Tea Non Boba Large",
    nutrition: {
      //correct
      small: {
        serving_size: 400,
        calories: 325,
        total_fat: [14, 18],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [48, 17],
        dietary_fiber: [0, 0],
        total_sugars: 27,
        added_sugars: [0, 0],
        protein: [1, 2],
      },

      large: {
        serving_size: 520,
        calories: 422,
        total_fat: [18, 18],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [62, 17],
        dietary_fiber: [0, 0],
        total_sugars: 35,
        added_sugars: [0, 0],
        protein: [1, 2],
      },
    },
  },

  {
    id: 5,
    htmlid: "oolongmilktea",
    name: "Roasted Oolong Milk Tea",
    image: "../assets/Final/oolong_jelly_small.jpg",
    desc: "Experience the perfect harmony of flavors with our Roasted Oolong Milk Tea. This captivating beverage blends the robust and toasty notes of roasted oolong tea with the creamy indulgence of milk. With each sip, you'll be greeted by the rich and satisfying flavors of the roasted oolong, which deliver a warm and comforting sensation.",
    smallName: "Roast Oolong Milk Tea Small",
    largeName: "Roast Oolong Milk Tea Large",
    smallNameNB: "Roast Oolong Milk Tea Non Boba Small",
    largeNameNB: "Roast Oolong Milk Tea Non Boba Large",
    nutrition: {
      //correct
      small: {
        serving_size: 400,
        calories: 332,
        total_fat: [14, 18],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [49, 18],
        dietary_fiber: [0, 0],
        total_sugars: 30,
        added_sugars: [0, 0],
        protein: [1, 2],
      },

      large: {
        serving_size: 400,
        calories: 431,
        total_fat: [18, 18],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [64, 18],
        dietary_fiber: [0, 0],
        total_sugars: 39,
        added_sugars: [0, 0],
        protein: [1, 2],
      },
    },
  },
  {
    //missing
    id: 6,
    htmlid: "matchamilktea",
    name: "Matcha Milk Tea",
    image: "../assets/Final/matcha_small.jpg",
    desc: `Elevate your tea experience with the exquisite Matcha Milk Tea. This delightful beverage combines the vibrant and earthy flavors of matcha green tea with the creamy smoothness of milk. With every sip, you'll be enveloped in the rich, vegetal notes of finely ground matcha, known for its energizing properties and antioxidant benefits. Whether you're a matcha lover or simply looking for a unique and satisfying drink, our Matcha Milk Tea offers a harmonious blend of tradition and modernity. Immerse yourself in the captivating essence of matcha and the creamy delight of milk, and discover a truly delightful tea experience that nourishes both body and soul.`,
    smallName: "Matcha Milk Tea Small",
    largeName: "Matcha Milk Tea Large",
    nutrition: {
      //correct
      small: {
        serving_size: 400,
        calories: 325,
        total_fat: [14, 18],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [48, 17],
        dietary_fiber: [0, 0],
        total_sugars: 27,
        added_sugars: [0, 0],
        protein: [1, 2],
      },

      // large: {
      //   serving_size: 400,
      //   calories: 332,
      //   total_fat: [14, 18],
      //   saturated_fat: [0, 0],
      //   trans_fat: 0,
      //   sodium: [0, 0],
      //   total_carbohydrate: [49, 18],
      //   dietary_fiber: [0, 0],
      //   total_sugars: 30,
      //   added_sugars: [0, 0],
      //   protein: [1, 2],
      // },
    },
  },

  {
    id: 7,
    htmlid: "taromilktea",
    name: "Taro Milk Tea",
    image: "../assets/Final/taro_small.jpg",
    desc: `Delight in the unique and captivating flavors of Taro Milk Tea. This enchanting beverage combines the earthy sweetness of taro root with the creamy richness of milk. Each sip offers a delightful balance of flavors, with the subtle nuttiness of taro complemented by the velvety smoothness of milk. The result is a comforting and indulgent drink that will leave you craving for more. Whether you're a fan of taro or simply looking for a new and delicious treat, our Taro Milk Tea is a delightful journey for your taste buds. Immerse yourself in the distinct charm of taro and the creamy embrace of milk, and experience a truly unforgettable tea experience.`,
    smallName: "Taro Jasmine Milk Tea Small",
    largeName: "Taro Jasmine Milk Tea Large",
    nutrition: {
      //correct
      small: {
        serving_size: 400,
        calories: 330,
        total_fat: [14, 18],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [45, 2],
        total_carbohydrate: [0, 0],
        dietary_fiber: [0, 0],
        total_sugars: 0,
        added_sugars: [28, 56],
        protein: [1, 2],
      },
    },
  },

  {
    id: 8,
    htmlid: "coffeemilktea",
    name: "Coffee Milk Tea",
    image: "../assets/Final/coffee_mt_small.jpg",
    desc: `Discover the perfect fusion of two beloved beverages with our Coffee Milk Tea. This harmonious blend combines the rich and bold flavors of coffee with the creamy indulgence of milk tea. Each sip tantalizes your taste buds with the robust and aromatic notes of coffee, perfectly balanced by the smooth and velvety texture of milk tea. Indulge in the best of both worlds as you savor the energizing kick of coffee alongside the comforting creaminess of milk tea. Whether you're a coffee enthusiast or a tea lover, our Coffee Milk Tea offers a delightful union that will awaken your senses and leave you craving for more. Immerse yourself in this enticing blend and experience a truly exceptional beverage that satisfies your coffee and tea cravings in one sip.`,
    sizeName: "Coffee Milk Tea (Jasmine) Large",
    nutrition: {
      small: {
        serving_size: 546,
        calories: 431,
        total_fat: [16, 15],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [75, 18],
        dietary_fiber: [0, 0],
        total_sugars: 47,
        added_sugars: [0, 0],
        protein: [4, 7],
      },
    },
  },
  {
    id: 9,
    htmlid: "thaiicedtea",
    name: "Thai Iced Tea",
    image: "../assets/Final/thai_tea_small.jpg",
    smallName: "Thai Iced Tea Small",
    largeName: "Thai Iced Tea Large",
    desc: `
    Immerse yourself in the vibrant flavors of Thailand with our tantalizing Thai Iced Tea. This iconic beverage combines the bold and aromatic black tea with a touch of sweetness from condensed milk, creating a harmonious balance of flavors. Served over ice, this refreshing drink offers a delightful combination of robust tea notes and creamy indulgence. The vibrant orange color adds to its visual appeal, making it an irresistible choice. Whether you're seeking a cooling respite on a sunny day or looking to savor a taste of Thai cuisine, our Thai Iced Tea is a true delight for your senses. Experience the exotic charm of Thailand in every sip and let the refreshing flavors transport you to the bustling streets of Bangkok.`,
    nutrition: {
      small: {
        serving_size: 425,
        calories: 374,
        total_fat: [13, 17],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [56, 20],
        dietary_fiber: [0, 0],
        total_sugars: 42,
        added_sugars: [0, 0],
        protein: [4, 8],
      },

      large: {
        serving_size: 553,
        calories: 486,
        total_fat: [17, 17],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [73, 20],
        dietary_fiber: [0, 0],
        total_sugars: 55,
        added_sugars: [0, 0],
        protein: [5, 8],
      },
    },
  },

  {
    id: 10,
    htmlid: "vietnamesecoffee",
    name: "Vietnamese Coffee",
    smallName: "Vietnamese Coffee Small",
    largeName: "Vietnamese Coffee Large",
    image: "../assets/Final/coffee_small.jpg",
    desc: `Immerse yourself in the bold and captivating flavors of Vietnamese Coffee. This iconic drink captures the essence of Vietnam's vibrant coffee culture, delivering a rich and invigorating experience. Made with finely ground Vietnamese beans and brewed through a traditional drip filter, each sip unveils a robust and full-bodied coffee profile that is both aromatic and satisfying. Paired with a touch of sweetened condensed milk, this coffee achieves a perfect balance of bitterness and creaminess, creating a delightful treat for your taste buds. Indulge in the cultural heritage and unique character of Vietnamese Coffee, and let it transport you to the bustling streets of Vietnam, where savoring a cup of this coffee is an essential part of daily life.`,
    nutrition: {
      small: {
        serving_size: 420,
        calories: 340,
        total_fat: [10, 13],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [52, 19],
        dietary_fiber: [0, 0],
        total_sugars: 47,
        added_sugars: [0, 0],
        protein: [6, 12],
      },

      large: {
        serving_size: 546,
        calories: 442,
        total_fat: [13, 13],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [68, 19],
        dietary_fiber: [0, 0],
        total_sugars: 61,
        added_sugars: [0, 0],
        protein: [8, 12],
      },
    },
  },
  {
    id: 11,
    htmlid: "mangolassi",
    name: "Mango Lassi",
    smallName: "Mango Lassi Small",
    largeName: "Mango Lassi Large",
    image: "../assets/Final/lassi-removebg-preview.png",
    desc: `Escape to a tropical oasis with our refreshing Mango Lassi. This creamy and indulgent beverage is a delightful blend of ripe, succulent mangoes and creamy yogurt. With each sip, you'll be transported to sun-kissed orchards, as the sweet and tangy flavors of fresh mango dance on your palate. The smooth and velvety yogurt adds a luscious texture, creating a perfect balance of richness and fruity delight. Indulge in this exotic delight and let the vibrant flavors transport you to a state of pure bliss.`,
    nutrition: {
      small: {
        serving_size: 420,
        calories: 378,
        total_fat: [10, 13],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [63, 23],
        dietary_fiber: [0, 0],
        total_sugars: 45,
        added_sugars: [0, 0],
        protein: [8, 16],
      },

      large: {
        serving_size: 546,
        calories: 491,
        total_fat: [13, 13],
        saturated_fat: [0, 0],
        trans_fat: 0,
        sodium: [0, 0],
        total_carbohydrate: [82, 23],
        dietary_fiber: [0, 0],
        total_sugars: 59,
        added_sugars: [0, 0],
        protein: [10, 16],
      },
    },
  },
];

export { menuobj, allItems };
